### ISSUE TITLE
Handling organizations with multiple variations: locations/subsidiaries/departments

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/domain-models#14]
Questions from Nate:

How should we handle organizations that have various multiples of addresses (same org, different locations), organization with subsidiaries, and organization with departments:

**A single organization has multiple locations**
- Would we have just one organization object with multiple addresses? Each location would be a part of the same org (same tax identifiers, same name, ownership, etc.) but would be a different physical location that may or may not have its own management, offerings, etc.
- If the above is true, how would we go about indicating a headquarters or main address?

**An organization with subsidiary organizations**
- Our thinking is that we would have multiple organizations and tie them together with schema:subOrganization and schema:parentOrganization since these would be distinct entities despite a hierarchical connection

**An organization with semi-independent departments** (i.e., a university with various departments)
- This appears to be the same basic scenario as the above, except that we would (according to the definition for schema:subOrganization) need to use schema:department instead of schema:subOrganization. Is this correct? Do university departments have distinct org identifiers that would set them sufficiently apart from their parent org?

**Comment by stuartasutton** [comment]
Nate, for single organization with multiple locations, you might use a single instance of organization using the "address" property of "Organization" for the headquarters and the "location" property for the multiple locations of that organization. 

I think your analysis of subsidiary is on target.

Similarly, your suggestions as to use of property "department" for academic units within a university also seems appropriate since they are subordinate to the university as organizations.  The range of "department" includes "Organization", so you'd have the full set of description options.  I think you are correct that the "suborganization"/"parentOrganization" does not capture it since the academic unit does not stand in an subsidiary relationship to the university (at least in my experience).

**Comment by siuccwd** [comment]
If the only purpose is to show an org has multiple addresses, then the locations as addresses is fine.

An important factor will be whether one or more of the ‘locations’ will have a separate role with a credential. As we only have Agent – Credential roles, we would not be able to create a role using an entity that is just an address.

**Comment by stuartasutton** [comment]
@siuccwd if an instance of organization has a separate role to play in the lifecycle of a credential, then I'd assume that organization would not be merely an address but separately described as an organization. Such an organization might nevertheless be a subordinate entity to another.
